### ISSUE TITLE
Send the user to a blank screen when they log in

### ISSUE THREAD

**Issue by akadir8** [octoposprime/op-fe-app#12]
This is a test issue

**Comment by husamettinarabaci** [comment]
You have to add some fields correctly for every issue.
Correct and a very large description.
Correct labels
Estimation time

Please add all of them to this issue.

**Comment by husamettinarabaci** [comment]
You can use it as an issue name;
"Redirect Log-in"
And You can use it as a description;
"The user will have to redirect the login page when..."

**Comment by husamettinarabaci** [comment]
Attention please
https://github.com/octoposprime/op-web-app/issues/12#issuecomment-2034161399

**Comment by akadir8** [comment]
This is an issue that was opened to conduct an experiment #12

**Comment by akadir8** [comment]
This issue was opened for testing purposes
