### ISSUE TITLE
Basic web app login page design in Figma

### ISSUE THREAD

**Issue by aminenurgynk** [octoposprime/op-fe-app#24]
Web App login page need a design made in Figma.
The design should be simple, focusing on functionality rather than aesthetics.
It needs to include fields for username or email and password, plus a login button.
Please ensure the design is user-friendly.

**Comment by husamettinarabaci** [comment]
Please add the correct labels.

**Comment by aminenurgynk** [comment]
' ui/ux ' seem correct label for this issue.

**Comment by akadir8** [comment]
This code has been postponed to a later date
